/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _exlcm_usb2000Spec_t_h
#define _exlcm_usb2000Spec_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _exlcm_usb2000Spec_t exlcm_usb2000Spec_t;
struct _exlcm_usb2000Spec_t
{
    int64_t    timestamp;
    int16_t    numSamples;
    char*      id;
    int32_t    *specData;
    int8_t     sixteenBitData;
    int16_t    startEndIdx[2];
    int16_t    intTime;
};

exlcm_usb2000Spec_t   *exlcm_usb2000Spec_t_copy(const exlcm_usb2000Spec_t *p);
void exlcm_usb2000Spec_t_destroy(exlcm_usb2000Spec_t *p);

typedef struct _exlcm_usb2000Spec_t_subscription_t exlcm_usb2000Spec_t_subscription_t;
typedef void(*exlcm_usb2000Spec_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const exlcm_usb2000Spec_t *msg, void *user);

int exlcm_usb2000Spec_t_publish(lcm_t *lcm, const char *channel, const exlcm_usb2000Spec_t *p);
exlcm_usb2000Spec_t_subscription_t* exlcm_usb2000Spec_t_subscribe(lcm_t *lcm, const char *channel, exlcm_usb2000Spec_t_handler_t f, void *userdata);
int exlcm_usb2000Spec_t_unsubscribe(lcm_t *lcm, exlcm_usb2000Spec_t_subscription_t* hid);
int exlcm_usb2000Spec_t_subscription_set_queue_capacity(exlcm_usb2000Spec_t_subscription_t* subs,
                              int num_messages);


int  exlcm_usb2000Spec_t_encode(void *buf, int offset, int maxlen, const exlcm_usb2000Spec_t *p);
int  exlcm_usb2000Spec_t_decode(const void *buf, int offset, int maxlen, exlcm_usb2000Spec_t *p);
int  exlcm_usb2000Spec_t_decode_cleanup(exlcm_usb2000Spec_t *p);
int  exlcm_usb2000Spec_t_encoded_size(const exlcm_usb2000Spec_t *p);

// LCM support functions. Users should not call these
int64_t __exlcm_usb2000Spec_t_get_hash(void);
int64_t __exlcm_usb2000Spec_t_hash_recursive(const __lcm_hash_ptr *p);
int     __exlcm_usb2000Spec_t_encode_array(void *buf, int offset, int maxlen, const exlcm_usb2000Spec_t *p, int elements);
int     __exlcm_usb2000Spec_t_decode_array(const void *buf, int offset, int maxlen, exlcm_usb2000Spec_t *p, int elements);
int     __exlcm_usb2000Spec_t_decode_array_cleanup(exlcm_usb2000Spec_t *p, int elements);
int     __exlcm_usb2000Spec_t_encoded_array_size(const exlcm_usb2000Spec_t *p, int elements);
int     __exlcm_usb2000Spec_t_clone_array(const exlcm_usb2000Spec_t *p, exlcm_usb2000Spec_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
