/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "exlcm_usb2000Spec_t.h"

static int __exlcm_usb2000Spec_t_hash_computed;
static int64_t __exlcm_usb2000Spec_t_hash;

int64_t __exlcm_usb2000Spec_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __exlcm_usb2000Spec_t_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__exlcm_usb2000Spec_t_get_hash };
    (void) cp;

    int64_t hash = 0x3269485fd9aba2f4LL
         + __int64_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __exlcm_usb2000Spec_t_get_hash(void)
{
    if (!__exlcm_usb2000Spec_t_hash_computed) {
        __exlcm_usb2000Spec_t_hash = __exlcm_usb2000Spec_t_hash_recursive(NULL);
        __exlcm_usb2000Spec_t_hash_computed = 1;
    }

    return __exlcm_usb2000Spec_t_hash;
}

int __exlcm_usb2000Spec_t_encode_array(void *buf, int offset, int maxlen, const exlcm_usb2000Spec_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].numSamples), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, p[element].specData, p[element].numSamples);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].sixteenBitData), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].startEndIdx, 2);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].intTime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int exlcm_usb2000Spec_t_encode(void *buf, int offset, int maxlen, const exlcm_usb2000Spec_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __exlcm_usb2000Spec_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __exlcm_usb2000Spec_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __exlcm_usb2000Spec_t_encoded_array_size(const exlcm_usb2000Spec_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __int16_t_encoded_array_size(&(p[element].numSamples), 1);

        size += __string_encoded_array_size(&(p[element].id), 1);

        size += __int32_t_encoded_array_size(p[element].specData, p[element].numSamples);

        size += __boolean_encoded_array_size(&(p[element].sixteenBitData), 1);

        size += __int16_t_encoded_array_size(p[element].startEndIdx, 2);

        size += __int16_t_encoded_array_size(&(p[element].intTime), 1);

    }
    return size;
}

int exlcm_usb2000Spec_t_encoded_size(const exlcm_usb2000Spec_t *p)
{
    return 8 + __exlcm_usb2000Spec_t_encoded_array_size(p, 1);
}

int __exlcm_usb2000Spec_t_decode_array(const void *buf, int offset, int maxlen, exlcm_usb2000Spec_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].numSamples), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].specData = (int32_t*) lcm_malloc(sizeof(int32_t) * p[element].numSamples);
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, p[element].specData, p[element].numSamples);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].sixteenBitData), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].startEndIdx, 2);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].intTime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __exlcm_usb2000Spec_t_decode_array_cleanup(exlcm_usb2000Spec_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __int16_t_decode_array_cleanup(&(p[element].numSamples), 1);

        __string_decode_array_cleanup(&(p[element].id), 1);

        __int32_t_decode_array_cleanup(p[element].specData, p[element].numSamples);
        if (p[element].specData) free(p[element].specData);

        __boolean_decode_array_cleanup(&(p[element].sixteenBitData), 1);

        __int16_t_decode_array_cleanup(p[element].startEndIdx, 2);

        __int16_t_decode_array_cleanup(&(p[element].intTime), 1);

    }
    return 0;
}

int exlcm_usb2000Spec_t_decode(const void *buf, int offset, int maxlen, exlcm_usb2000Spec_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __exlcm_usb2000Spec_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __exlcm_usb2000Spec_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int exlcm_usb2000Spec_t_decode_cleanup(exlcm_usb2000Spec_t *p)
{
    return __exlcm_usb2000Spec_t_decode_array_cleanup(p, 1);
}

int __exlcm_usb2000Spec_t_clone_array(const exlcm_usb2000Spec_t *p, exlcm_usb2000Spec_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __int16_t_clone_array(&(p[element].numSamples), &(q[element].numSamples), 1);

        __string_clone_array(&(p[element].id), &(q[element].id), 1);

        q[element].specData = (int32_t*) lcm_malloc(sizeof(int32_t) * q[element].numSamples);
        __int32_t_clone_array(p[element].specData, q[element].specData, p[element].numSamples);

        __boolean_clone_array(&(p[element].sixteenBitData), &(q[element].sixteenBitData), 1);

        __int16_t_clone_array(p[element].startEndIdx, q[element].startEndIdx, 2);

        __int16_t_clone_array(&(p[element].intTime), &(q[element].intTime), 1);

    }
    return 0;
}

exlcm_usb2000Spec_t *exlcm_usb2000Spec_t_copy(const exlcm_usb2000Spec_t *p)
{
    exlcm_usb2000Spec_t *q = (exlcm_usb2000Spec_t*) malloc(sizeof(exlcm_usb2000Spec_t));
    __exlcm_usb2000Spec_t_clone_array(p, q, 1);
    return q;
}

void exlcm_usb2000Spec_t_destroy(exlcm_usb2000Spec_t *p)
{
    __exlcm_usb2000Spec_t_decode_array_cleanup(p, 1);
    free(p);
}

int exlcm_usb2000Spec_t_publish(lcm_t *lc, const char *channel, const exlcm_usb2000Spec_t *p)
{
      int max_data_size = exlcm_usb2000Spec_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = exlcm_usb2000Spec_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _exlcm_usb2000Spec_t_subscription_t {
    exlcm_usb2000Spec_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void exlcm_usb2000Spec_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    exlcm_usb2000Spec_t p;
    memset(&p, 0, sizeof(exlcm_usb2000Spec_t));
    status = exlcm_usb2000Spec_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding exlcm_usb2000Spec_t!!!\n", status);
        return;
    }

    exlcm_usb2000Spec_t_subscription_t *h = (exlcm_usb2000Spec_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    exlcm_usb2000Spec_t_decode_cleanup (&p);
}

exlcm_usb2000Spec_t_subscription_t* exlcm_usb2000Spec_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    exlcm_usb2000Spec_t_handler_t f, void *userdata)
{
    exlcm_usb2000Spec_t_subscription_t *n = (exlcm_usb2000Spec_t_subscription_t*)
                       malloc(sizeof(exlcm_usb2000Spec_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 exlcm_usb2000Spec_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg exlcm_usb2000Spec_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int exlcm_usb2000Spec_t_subscription_set_queue_capacity (exlcm_usb2000Spec_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int exlcm_usb2000Spec_t_unsubscribe(lcm_t *lcm, exlcm_usb2000Spec_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe exlcm_usb2000Spec_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

