all: multiplotwindowui.py plotdialogui.py

multiplotwindowui.py: multiplotwindow.ui
	pyuic5 multiplotwindow.ui > multiplotwindowui.py

plotdialogui.py: plotdialog.ui
	pyuic5 plotdialog.ui > plotdialogui.py
