# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multiplotwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.sourceView = DragTreeView(self.layoutWidget)
        self.sourceView.setObjectName("sourceView")
        self.verticalLayout_2.addWidget(self.sourceView)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.potentialView = QtWidgets.QListView(self.layoutWidget1)
        self.potentialView.setObjectName("potentialView")
        self.verticalLayout.addWidget(self.potentialView)
        self.verticalLayout_4.addWidget(self.splitter)
        self.addplotbutton = QtWidgets.QPushButton(self.groupBox_2)
        self.addplotbutton.setObjectName("addplotbutton")
        self.verticalLayout_4.addWidget(self.addplotbutton)
        self.groupBox = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.activeView = QtWidgets.QTreeView(self.groupBox)
        self.activeView.setObjectName("activeView")
        self.verticalLayout_3.addWidget(self.activeView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.deleteplotbutton = QtWidgets.QPushButton(self.groupBox)
        self.deleteplotbutton.setObjectName("deleteplotbutton")
        self.horizontalLayout_2.addWidget(self.deleteplotbutton)
        self.swapaxesbutton = QtWidgets.QPushButton(self.groupBox)
        self.swapaxesbutton.setObjectName("swapaxesbutton")
        self.horizontalLayout_2.addWidget(self.swapaxesbutton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.plotView = DropPlotWidget(self.splitter_3)
        self.plotView.setObjectName("plotView")
        self.horizontalLayout.addWidget(self.splitter_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1028, 19))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LCM Data Plot"))
        self.groupBox_2.setTitle(_translate("MainWindow", "New Plots"))
        self.label.setText(_translate("MainWindow", "Y"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.addplotbutton.setText(_translate("MainWindow", "Add Plot"))
        self.groupBox.setTitle(_translate("MainWindow", "Active Plots"))
        self.deleteplotbutton.setText(_translate("MainWindow", "Delete Plot"))
        self.swapaxesbutton.setText(_translate("MainWindow", "Swap X and Y"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))

from .dragtree import DragTreeView
from .dropplot import DropPlotWidget
