# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotdialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotDialog(object):
    def setupUi(self, PlotDialog):
        PlotDialog.setObjectName("PlotDialog")
        PlotDialog.resize(248, 395)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlotDialog.sizePolicy().hasHeightForWidth())
        PlotDialog.setSizePolicy(sizePolicy)
        PlotDialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.point_group = QtWidgets.QGroupBox(PlotDialog)
        self.point_group.setObjectName("point_group")
        self.gridLayout = QtWidgets.QGridLayout(self.point_group)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.point_group)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.point_size = QtWidgets.QDoubleSpinBox(self.point_group)
        self.point_size.setDecimals(1)
        self.point_size.setMinimum(0.5)
        self.point_size.setMaximum(10.0)
        self.point_size.setProperty("value", 2.5)
        self.point_size.setObjectName("point_size")
        self.gridLayout.addWidget(self.point_size, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.point_group)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.point_fill_colour = QtWidgets.QPushButton(self.point_group)
        self.point_fill_colour.setObjectName("point_fill_colour")
        self.gridLayout.addWidget(self.point_fill_colour, 4, 1, 1, 1)
        self.point_outline_colour = QtWidgets.QPushButton(self.point_group)
        self.point_outline_colour.setObjectName("point_outline_colour")
        self.gridLayout.addWidget(self.point_outline_colour, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.point_group)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.point_group)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.point_outline_width = QtWidgets.QDoubleSpinBox(self.point_group)
        self.point_outline_width.setDecimals(1)
        self.point_outline_width.setMaximum(10.0)
        self.point_outline_width.setSingleStep(0.5)
        self.point_outline_width.setObjectName("point_outline_width")
        self.gridLayout.addWidget(self.point_outline_width, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.point_group)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.point_style = QtWidgets.QComboBox(self.point_group)
        self.point_style.setObjectName("point_style")
        self.gridLayout.addWidget(self.point_style, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.point_group)
        self.line_group = QtWidgets.QGroupBox(PlotDialog)
        self.line_group.setFlat(False)
        self.line_group.setObjectName("line_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.line_group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_width = QtWidgets.QDoubleSpinBox(self.line_group)
        self.line_width.setDecimals(1)
        self.line_width.setMinimum(0.5)
        self.line_width.setMaximum(10.0)
        self.line_width.setSingleStep(0.5)
        self.line_width.setObjectName("line_width")
        self.gridLayout_2.addWidget(self.line_width, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.line_group)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.line_colour = QtWidgets.QPushButton(self.line_group)
        self.line_colour.setText("")
        self.line_colour.setObjectName("line_colour")
        self.gridLayout_2.addWidget(self.line_colour, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.line_group)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.line_group)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.line_style = QtWidgets.QComboBox(self.line_group)
        self.line_style.setObjectName("line_style")
        self.gridLayout_2.addWidget(self.line_style, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.line_group)
        self.graphicsView = QtWidgets.QGraphicsView(PlotDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 40))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 40))
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setInteractive(False)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.buttonBox = QtWidgets.QDialogButtonBox(PlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PlotDialog)
        self.buttonBox.accepted.connect(PlotDialog.accept)
        self.buttonBox.rejected.connect(PlotDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PlotDialog)

    def retranslateUi(self, PlotDialog):
        _translate = QtCore.QCoreApplication.translate
        PlotDialog.setWindowTitle(_translate("PlotDialog", "Plot Style"))
        self.point_group.setTitle(_translate("PlotDialog", "Point"))
        self.label_7.setText(_translate("PlotDialog", "Point Fill Colour"))
        self.point_size.setSuffix(_translate("PlotDialog", "px"))
        self.label_2.setText(_translate("PlotDialog", "Point Diameter"))
        self.label_5.setText(_translate("PlotDialog", "Point Outline Colour"))
        self.label_8.setText(_translate("PlotDialog", "Point Outline Width"))
        self.point_outline_width.setSuffix(_translate("PlotDialog", "px"))
        self.label_3.setText(_translate("PlotDialog", "Point Style"))
        self.line_group.setTitle(_translate("PlotDialog", "Line"))
        self.line_width.setSuffix(_translate("PlotDialog", "px"))
        self.label.setText(_translate("PlotDialog", "Line Width"))
        self.label_6.setText(_translate("PlotDialog", "Line Colour"))
        self.label_4.setText(_translate("PlotDialog", "Line Style"))

