function TimePlot(plotfun)

clf(figure(1));
user = get(1,'UserData');
ctlhdl = get(2,'UserData');

try
    iver_t = evalin('base','iver_t');
    IVER=1;
catch
    IVER=0;
end

if isfield('user','STARTTIME') && user.STARTTIME==0
  errordlg('Select a mission file first!','Error');
  return;
end

% need to draw the other subplot?
try
    top_cur = user.PH_TOP;
catch
    top_cur = [];
end
try
    bottom_cur = user.PH_BOTTOM;
catch
    bottom_cur = [];
end

% handle for two subplot, when full h1=full, h2=null
if (get(ctlhdl.top_radiobutton,'Value') == 1) % top
    if (~isempty(bottom_cur))
        subplot(2,1,2); eval(bottom_cur);
        SetPlotSize;
        grid on;
        
        if (~(strcmp(plotfun,'pow_batt_perc') || ...
            strcmp(bottom_cur,'pow_batt_perc')) || ...
            get(ctlhdl.review_slider,'Value') ~= -1)
            SetHour;
        end

        if (get(ctlhdl.setwin_checkbox,'Value') == 1)
            range = get(ctlhdl.setwin_checkbox,'UserData');
            setwin(range);
        end
    end
elseif (get(ctlhdl.bottom_radiobutton,'Value') == 1)
    if (~isempty(top_cur))
        subplot(2,1,1); eval(top_cur);
        SetPlotSize;
        grid on;
        
        if (~(strcmp(top_cur,'pow_batt_perc') || ...
            strcmp(plotfun,'pow_batt_perc')) || ...
            get(ctlhdl.review_slider,'Value') ~= -1)
            SetHour;
        end

        if (get(ctlhdl.setwin_checkbox,'Value') == 1)
            range = get(ctlhdl.setwin_checkbox,'UserData');
            setwin(range);
        end
    end
end

ClearXYPosControls;
[h,subtype] = SetSubPlot;
if (subtype == 0) % full
    SetupMaskControls(plotfun, '', h, subtype);
    figure(1);
elseif (subtype == 1) % top
    SetupMaskControls(plotfun, bottom_cur, '', subtype);
    subplot(2,1,1);
else % bottom
    SetupMaskControls(top_cur, plotfun, '', subtype);
    subplot(2,1,2);
end
eval(plotfun);
SetPlotSize;
grid on;

if (~(strcmp(plotfun,'pow_batt_perc') || ...
    strcmp(top_cur,'pow_batt_perc') || ...
    strcmp(bottom_cur,'pow_batt_perc')) || ...    
    get(ctlhdl.review_slider,'Value') ~= -1) 
    SetHour;
end

if (get(ctlhdl.setwin_checkbox,'Value') == 1)
  range = get(ctlhdl.setwin_checkbox,'UserData');
  setwin(range);
end 

SetTimeAxisFormat;
DisableDataCursorMode;

% remember the current configuration
if (subtype == 1) % top
    user.PH_TOP = plotfun;
    user.PH_FULL = '';
elseif (subtype == 2) % bottom
    user.PH_BOTTOM = plotfun;
    user.PH_FULL = '';
else
    user.PH_FULL = plotfun;
    user.PH_TOP = '';
    user.PH_BOTTOM = '';
end
set(1,'UserData',user);

%==========================================================================
function DisableDataCursorMode
	dcm_obj = datacursormode(gcf);
	set(dcm_obj, 'Enable', 'off');
  
%==========================================================================
function ClearXYPosControls

	kids = get(1,'Children');
	for ii=1:length(kids)
	  if strcmp(get(kids(ii),'Tag'),'subplot_frame_position')
		figure(1); clf;
		set(1,'UserData','');
		break;
	  end;
	end
  
%==========================================================================
function SetupMaskControls(plotfun1, plotfun2, h, subtype)
	%================================  
	% subplot controls
    % Adjust GPS, state of the vehicle in SetupXYControls
	%================================  
	figplt = figure(1);% clf;
    
    chbx_h = 25; gps_box_w = 50; curst_box_w = 80; leak_box_w = 50; goal_box_w = 60;
    chkbox_frame_pos = [10, 10, gps_box_w + curst_box_w + leak_box_w + goal_box_w+10, 30];    
    chk_gps_pos = [chkbox_frame_pos(1) chkbox_frame_pos(2) gps_box_w chbx_h];
    chk_curst_pos = [chkbox_frame_pos(1)+gps_box_w chkbox_frame_pos(2) curst_box_w chbx_h];
    chk_leak_pos = [chkbox_frame_pos(1)+gps_box_w+curst_box_w,...
                    chkbox_frame_pos(2), leak_box_w, chbx_h];
    chk_goal_pos = [chkbox_frame_pos(1)+gps_box_w+curst_box_w+leak_box_w,...
                    chkbox_frame_pos(2), goal_box_w, chbx_h];
    
    dt_frame_pos = [chkbox_frame_pos(3)+10, chkbox_frame_pos(2), 20, 15];
    dt_edit_pos = [chkbox_frame_pos(3)+30, chkbox_frame_pos(2), 30, 15];
    
    % frame containing checkboxes for masks
	plthdl.subplot_frame = ...
		uicontrol('Parent',figplt, ...
			  'Units','pixels', ...
			  'BackgroundColor',[0.7 0.7 0.7], ...
			  'ListboxTop',0, ...
			  'Position',[chkbox_frame_pos(1)-2 chkbox_frame_pos(2)-2 chkbox_frame_pos(3) chkbox_frame_pos(4)], ...
			  'Style','frame', ...
			  'Tag','subplot_frame');


    %make a command specific to the subplot top or full    
    plotfuncmd1 = sprintf('eval(''%s'');',plotfun1);
    hstr1 = sprintf('h%d',1);
    assignin('base',hstr1,h);
    subpltcmd1 = ['eval(''subplot(' hstr1 ')'');'];

    %make a command specific to the subplot bottom
    plotfuncmd2 = sprintf('eval(''%s'');',plotfun2);

    if (subtype == 0)
        plthdl.imagpsvalid_checkbox = ...
            uicontrol('Parent',figplt, ...
            'Units','pixels', ...
            'BackgroundColor',[0.7 0.7 0.7], ...
            'Value',0, ...
            'Callback', ...
            ['plthdl = subplot_handle;', ...
            subpltcmd1,...
            'axe = axis;', ...
            plotfuncmd1, ...
            'axis(axe);', ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.imagpsvalid_checkbox,''Value'')==1);', ...
            'set(plthdl.imacurrent_step_checkbox,''Value'',0);',...
            'set(plthdl.imaleak_step_checkbox,''Value'',0);',...
            'set(plthdl.goalpoint_checkbox,''Value'',0);', ...
            'drawnow;', ...
            'imagpsvalid;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'clear plthdl axe;', ...
            ], ...
            'ListboxTop',0, ...
            'Position',chk_gps_pos, ...
            'String','gps', ...
            'HorizontalAlignment','left', ...
            'Style','checkbox', ...
            'Tag','imagpsvalid_checkbox');
        plthdl.imacurrent_step_checkbox = ...
            uicontrol('Parent',figplt, ...
            'Units','pixels', ...
            'BackgroundColor',[0.7 0.7 0.7], ...
            'Value',0, ...
            'Callback', ...
            ['plthdl = subplot_handle;', ...
            subpltcmd1,...
            'axe = axis;', ...
            plotfuncmd1, ...
            'axis(axe);', ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.imacurrent_step_checkbox,''Value'')==1);', ...
            'set(plthdl.imagpsvalid_checkbox,''Value'',0);',...
            'set(plthdl.imaleak_step_checkbox,''Value'',0);',...
            'set(plthdl.goalpoint_checkbox,''Value'',0);', ...
            'drawnow;', ...
            'imacurrent_step;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'clear plthdl axe;', ...
            ], ...
            'ListboxTop',0, ...
            'Position',chk_curst_pos, ...
            'String','curr. step', ...
            'HorizontalAlignment','left', ...
            'Style','checkbox', ...
            'Tag','imacurrent_step_checkbox');
        plthdl.imaleak_step_checkbox = ...
            uicontrol('Parent',figplt, ...
            'Units','pixels', ...
            'BackgroundColor',[0.7 0.7 0.7], ...
            'Value',0, ...
            'Callback', ...
            ['plthdl = subplot_handle;', ...
            subpltcmd1,...
            'axe = axis;', ...
            plotfuncmd1, ...
            'axis(axe);', ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.imaleak_step_checkbox,''Value'')==1 );', ...
            'set(plthdl.imagpsvalid_checkbox,''Value'',0);',...
            'set(plthdl.imacurrent_step_checkbox,''Value'',0);',...
            'set(plthdl.goalpoint_checkbox,''Value'',0);', ...
            'drawnow;', ...
            'imaleak_status;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'clear plthdl axe;', ...
            ], ...
            'ListboxTop',0, ...
            'Position',chk_leak_pos, ...
            'String','leak', ...
            'HorizontalAlignment','left', ...
            'Style','checkbox', ...
            'Tag','imaleak_status_checkbox');

        plthdl.goalpoint_checkbox = ...
            uicontrol('Parent',figplt, ...
            'Units','pixels', ...
            'BackgroundColor',[0.7 0.7 0.7], ...
            'Value',0, ...
            'Callback', ...
            ['plthdl = subplot_handle;', ...
            subpltcmd1,...
            'axe = axis;', ...
            plotfuncmd1, ...
            'axis(axe);', ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.goalpoint_checkbox,''Value'')==1);', ...
            'set(plthdl.imacurrent_step_checkbox,''Value'',0);',...
            'set(plthdl.imaleak_step_checkbox,''Value'',0);',...
            'set(plthdl.imagpsvalid_checkbox,''Value'',0);',...
            'drawnow;', ...
            'imagoalpoint;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'clear plthdl axe;', ...
            ], ...
            'ListboxTop',0, ...
            'Position',chk_goal_pos, ...
            'String','goal pt.', ...
            'HorizontalAlignment','left', ...
            'Style','checkbox', ...
            'Tag','imagpsvalid_checkbox');
    else
        plthdl.imagpsvalid_checkbox = ...
            uicontrol('Parent',figplt, ...
            'Units','pixels', ...
            'BackgroundColor',[0.7 0.7 0.7], ...
            'Value',0, ...
            'Callback', ...
            ['plthdl = subplot_handle;', ...
            'subplot(2,1,1);',... % top
            plotfuncmd1, ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.imagpsvalid_checkbox,''Value'')==1);', ...
            'set(plthdl.imacurrent_step_checkbox,''Value'',0);',...
            'set(plthdl.imaleak_step_checkbox,''Value'',0);',...
            'set(plthdl.goalpoint_checkbox,''Value'',0);', ...
            'drawnow;', ...
            'imagpsvalid;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'subplot(2,1,2);',... % bottom
            plotfuncmd2, ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.imagpsvalid_checkbox,''Value'')==1);', ...
            'set(plthdl.imacurrent_step_checkbox,''Value'',0);',...
            'set(plthdl.imaleak_step_checkbox,''Value'',0);',...
            'set(plthdl.goalpoint_checkbox,''Value'',0);', ...
            'drawnow;', ...
            'imagpsvalid;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'clear plthdl;'], ...
            'ListboxTop',0, ...
            'Position',chk_gps_pos, ...
            'String','gps', ...
            'HorizontalAlignment','left', ...
            'Style','checkbox', ...
            'Tag','imagpsvalid_checkbox');
        plthdl.imacurrent_step_checkbox = ...
            uicontrol('Parent',figplt, ...
            'Units','pixels', ...
            'BackgroundColor',[0.7 0.7 0.7], ...
            'Value',0, ...
            'Callback', ...
            ['plthdl = subplot_handle;', ...
            'subplot(2,1,1);',...   % top
            plotfuncmd1, ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.imacurrent_step_checkbox,''Value'')==1);', ...
            'set(plthdl.imagpsvalid_checkbox,''Value'',0);',...
            'set(plthdl.imaleak_step_checkbox,''Value'',0);',...
            'set(plthdl.goalpoint_checkbox,''Value'',0);', ...
            'drawnow;', ...
            'imacurrent_step;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'subplot(2,1,2);',...   % bottom
            plotfuncmd2, ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.imacurrent_step_checkbox,''Value'')==1);', ...
            'set(plthdl.imagpsvalid_checkbox,''Value'',0);',...
            'set(plthdl.imaleak_step_checkbox,''Value'',0);',...
            'set(plthdl.goalpoint_checkbox,''Value'',0);', ...
            'drawnow;', ...
            'imacurrent_step;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'clear plthdl;', ...
            ], ...
            'ListboxTop',0, ...
            'Position',chk_curst_pos, ...
            'String','curr. step', ...
            'HorizontalAlignment','left', ...
            'Style','checkbox', ...
            'Tag','imacurrent_step_checkbox');
        plthdl.imaleak_step_checkbox = ...
            uicontrol('Parent',figplt, ...
            'Units','pixels', ...
            'BackgroundColor',[0.7 0.7 0.7], ...
            'Value',0, ...
            'Callback', ...
            ['plthdl = subplot_handle;', ...
            'subplot(2,1,1);',...   % top
            plotfuncmd1, ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.imaleak_step_checkbox,''Value'')==1 );', ...
            'set(plthdl.imagpsvalid_checkbox,''Value'',0);',...
            'set(plthdl.imacurrent_step_checkbox,''Value'',0);',...
            'set(plthdl.goalpoint_checkbox,''Value'',0);', ...
            'drawnow;', ...
            'imaleak_status;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'subplot(2,1,2);',...   % bottom
            plotfuncmd2, ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.imaleak_step_checkbox,''Value'')==1 );', ...
            'set(plthdl.imagpsvalid_checkbox,''Value'',0);',...
            'set(plthdl.imacurrent_step_checkbox,''Value'',0);',...
            'set(plthdl.goalpoint_checkbox,''Value'',0);', ...
            'drawnow;', ...
            'imaleak_status;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'clear plthdl;', ...
            ], ...
            'ListboxTop',0, ...
            'Position',chk_leak_pos, ...
            'String','leak', ...
            'HorizontalAlignment','left', ...
            'Style','checkbox', ...
            'Tag','imaleak_status_checkbox');

        plthdl.goalpoint_checkbox = ...
            uicontrol('Parent',figplt, ...
            'Units','pixels', ...
            'BackgroundColor',[0.7 0.7 0.7], ...
            'Value',0, ...
            'Callback', ...
            ['plthdl = subplot_handle;', ...
            'subplot(2,1,1);',...   % top
            plotfuncmd1, ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.goalpoint_checkbox,''Value'')==1);', ...
            'set(plthdl.imacurrent_step_checkbox,''Value'',0);',...
            'set(plthdl.imaleak_step_checkbox,''Value'',0);',...
            'set(plthdl.imagpsvalid_checkbox,''Value'',0);',...
            'drawnow;', ...
            'imagoalpoint;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'subplot(2,1,2);',...   % bottom
            plotfuncmd2, ...
            'set(1,''pointer'',''watch'');', ...
            'if (get(plthdl.goalpoint_checkbox,''Value'')==1);', ...
            'set(plthdl.imacurrent_step_checkbox,''Value'',0);',...
            'set(plthdl.imaleak_step_checkbox,''Value'',0);',...
            'set(plthdl.imagpsvalid_checkbox,''Value'',0);',...
            'drawnow;', ...
            'imagoalpoint;', ...
            'end;', ...
            'set(1,''pointer'',''arrow'');', ...
            'SetPlotSize;', ...
            'SetDrag;', ...
            'grid on;', ...
            'clear plthdl;', ...
            ], ...
            'ListboxTop',0, ...
            'Position',chk_goal_pos, ...
            'String','goal pt.', ...
            'HorizontalAlignment','left', ...
            'Style','checkbox', ...
            'Tag','imagpsvalid_checkbox');
    end
	set(plthdl.subplot_frame,'UserData',plthdl);
