#!/usr/bin/env python
import lcm
import sys
import argparse

from lcmplot import get_message_types

if __name__ == '__main__':
    sys.path.insert(0, '/home/auv/git/acfr-lcm/build/lib/python2.7/dist-packages/perls/lcmtypes')

    parser = argparse.ArgumentParser()

    parser.add_argument('filename', type=str)

    args = parser.parse_args()

    import acfrlcm
    import senlcm
    import bot_core
    import bot_frames
    import bot_lcmgl
    import bot_param
    import bot_procman

    lcm_types = get_message_types(acfrlcm)
    lcm_types.update(get_message_types(senlcm))

    lcm_types.update(get_message_types(bot_core))
    lcm_types.update(get_message_types(bot_frames))
    lcm_types.update(get_message_types(bot_lcmgl))
    lcm_types.update(get_message_types(bot_param))
    lcm_types.update(get_message_types(bot_procman))

    from PyQt5.QtGui import QApplication
    qapp = QApplication([])

    # get the Qt Data Model ready for the plots
    from lcmplot.multisourcemodel import DataModel
    data_model = DataModel(parent=qapp)
    data_model.add_lcm_types(lcm_types)
    data_model.create_live()
    data_model.add_file(args.filename)

    from lcmplot import MultiSourcePlotWindow

    first_window = MultiSourcePlotWindow(data_model)
    first_window.show()

    qapp.exec_()


