#!/usr/bin/env python
import lcm
import sys
import curses
import curses.ascii

try:
    from cStringIO.StringIO import BytesIO
except:
    from io import BytesIO


def get_message_types(module_handle):

    fingerprint_mapping = {}

    possible_types = dir(module_handle)

    for ptype_name in possible_types:
        ptype = getattr(module_handle, ptype_name)
        if hasattr(ptype, '_packed_fingerprint'):
            fingerprint_mapping[ptype._get_packed_fingerprint()] = ptype

    return fingerprint_mapping


class Channel(object):
    def __init__(self, channel_name, data_type):
        self.channel_name = channel_name
        self.data_type = data_type
        self.latest = None
        self.subchannels = {}

    def decode(self, raw_data):
        if data_type is not None:
            return data_type.decode(buf)
        else:
            return None

    def handle_latest(self, raw_data):
        self.latest = raw_data

    def list_attributes(self, lcm_type_set, message=None):
        if self.data_type is None:
            return [("Can't decode", "")]

        message = message or self.data_type.decode(self.latest)
        attributes = [(self.channel_name, repr(message))]
        # pylcm uses slots to declare the variable elements so we
        # iterate over them, no need to check anything else
        for attr in message.__slots__:
            value = getattr(message, attr)
            if type(value) in lcm_type_set:
                # we have a 'subchannel' with an lcm type we know
                # so split it out and get the attributes.
                # just indent it a little
                if not attr in self.subchannels:
                    self.subchannels[attr] = Channel(attr, type(value))

                attributes.append((attr, repr(value)))

                # get all the subtypes attributes
                for attr, value in self.subchannels[attr].list_attributes(lcm_type_set, value):
                    attributes.append(('  ' + attr, '  ' + value))
                # don't want to append this
                continue
            else:
                value = unicode(value)

            # need to escape this as well, remove non-printable
            # characters
            attributes.append((attr, value))

        return attributes


class PySpy(object):
    def __init__(self, lcm_handle, lcm_types):
        self.lcm_handle = lcm_handle
        self.lcm_types = lcm_types
        self.lcm_type_set = set(lcm_types.values())
        
        lc.subscribe(".*", self.handle_message)

        self.channels = {}

    def handle_message(self, channel_name, raw_data):
        # if we haven't seen the channel
        # attempt detection
        if channel_name not in self.channels:
            self.detect_type(channel_name, raw_data)

        self.channels[channel_name].handle_latest(raw_data)

    def detect_type(self, channel_name, raw_data):
        buf = BytesIO(raw_data)

        fingerprint = buf.read(8)

        if fingerprint in self.lcm_types:
            data_type = self.lcm_types[fingerprint]
        else:
            data_type = None
        
        self.channels[channel_name] = Channel(channel_name, data_type)

class Interface(object):
    def __init__(self, spyinstance):
        self.col_widths = [29, 29, 20]  # the width of each channel
        self.col_starts = [0, 30, 60]
        self.selected_channel = None  # the name of the channel, not index
        self.last_attr_count = 0
        self.spyinstance = spyinstance

        # used for debuggin/messages, basically displays the last 10 rows...
        self.log = []

    def resize(self):
        # we expect a min width of 80, can probably handle less
        self.height, self.width = self.screen.getmaxyx()

        # we have two column separators
        if self.width > 80:
            self.col_widths = [29, 29, self.width - 60]
            self.col_starts = [0, 30, 60]
        else:
            # integer rounding, leave an extra column for divider
            fixed_width = self.width / 3 - 1
            self.col_widths = [fixed_width, fixed_width, self.width - 2 * fixed_width]
            self.col_starts = [0, fixed_width + 1, 2 * fixed_width + 2]

    def __call__(self, screen):
        self.screen = screen
        self.resize()

        self.screen.nodelay(1)

        quitting = False


        while not quitting:
            self.render()
            try:
                lc.handle()
            except IOError:
                break

            key = self.screen.getch()

            sorted_channels = sorted(self.spyinstance.channels.keys())
            if key == -1:
                continue

            elif key == curses.KEY_UP:
                if self.selected_channel is None:
                    self.selected_channel = sorted_channels[0]
                else:
                    index = sorted_channels.index(self.selected_channel) - 1
                    self.selected_channel = sorted_channels[index]

            elif key == curses.KEY_DOWN:
                if self.selected_channel is None:
                    self.selected_channel = sorted_channels[-1]
                else:
                    index = sorted_channels.index(self.selected_channel) + 1
                    if index >= len(sorted_channels):
                        index = 0
                    self.selected_channel = sorted_channels[index]

            elif key == ord('q') or key == ord('Q'):
                quitting = True

    def render(self):
        spy = self.spyinstance

        for i, name in enumerate(sorted(spy.channels.iterkeys())):
            if name == self.selected_channel:
                self.screen.addstr(i, self.col_starts[0], field(name, self.col_widths[0]), curses.A_BOLD)

                print_row = 0

                # print the attributes and their values
                attrs = spy.channels[name].list_attributes(spy.lcm_type_set)
                for attr, value in attrs:
                    self.screen.addstr(print_row, self.col_starts[1], field(attr, self.col_widths[1]))
                    try:
                        self.screen.addstr(print_row, self.col_starts[2], field(value, self.col_widths[2]))
                    except curses.error as e:
                        print e
                        
                    print_row += 1
                    if print_row >= self.height - 1:
                        # in case we overflow...
                        # should make a scrolling window...
                        break

                for j in xrange(print_row, self.last_attr_count):
                    self.screen.addstr(j, self.col_starts[1], field("", self.col_widths[1]))
                    self.screen.addstr(j, self.col_starts[2], field("", self.col_widths[2]))

                self.last_attr_count = print_row

            else:
                self.screen.addstr(i, self.col_starts[0], field(name, self.col_widths[0]))

        height = 30
        width = 80
        for i, row in enumerate(self.log[-10:-1]):
            self.screen.addstr(height-10+i, 0, field(name, width))

    

def field(string, width):
    printable = ""
    for c in string:
        try:
            printable += curses.ascii.unctrl(str(c))
        except UnicodeEncodeError:
            printable += c
    return printable.ljust(width)[:width]

if __name__ == '__main__':
    sys.path.insert(0, '/home/auv/git/acfr_lcm/build/lib/python2.7/dist-packages/perls/lcmtypes')

    import acfrlcm
    import senlcm
    import bot_core
    import bot_frames
    import bot_lcmgl
    import bot_param
    import bot_procman

    lcm_types = get_message_types(acfrlcm)
    lcm_types.update(get_message_types(senlcm))

    lcm_types.update(get_message_types(bot_core))
    lcm_types.update(get_message_types(bot_frames))
    lcm_types.update(get_message_types(bot_lcmgl))
    lcm_types.update(get_message_types(bot_param))
    lcm_types.update(get_message_types(bot_procman))

    lc = lcm.LCM()

    spy = PySpy(lc, lcm_types)
    interface = Interface(spy)

    curses.wrapper(interface)

