function Control_Window()
  
  % initalize the plot type window
  figctl = figure(2);  clf;
  set(figctl,'Name','Plot Controls', ...
	     'Menubar','none', ...
	     'NumberTitle','off', ...
	     'Resize','on', ...
	     'Units','pixels', ...
	     'Position',[18 15 875 135], ...
	     'Tag','figctl');


  %================================
  % data directory edit box
  %================================
  ctlhdl.dir_frame = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'ListboxTop',0, ...
		'Position',[0 65 221.76 40], ...
		'Style','frame', ...
		'Tag','dir_frame');
  ctlhdl.dir_edittext = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'ListboxTop',0, ...
		'Position',[3.84 67.44 213.12 20.8], ...
		'Callback','dir_callback()', ...
		'Style','edit', ...
		'Tag','dir_edittext');
  ctlhdl.dir_pushbutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[170 88 47 16], ...
        'Callback', ...
        ['ctlhdl = get(2,''UserData'');', ...
         'mydir = uigetdir();', ...
         'if mydir;', ...
           'set(ctlhdl.dir_edittext,''String'',mydir);', ...
           'dir_callback();', ...
         'end;', ...
         'clear mydir ctlhdl;', ...
        ], ...
		'Style','pushbutton', ...
		'String','Browse', ...
		'Tag','dir_pushbutton');
  
  %================================  
  % log files popup box
  %================================
  ctlhdl.log_frame = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'ListboxTop',0, ...
		'Position',[0 0 221.76 60], ...
		'Style','frame', ...
		'Tag','log_frame');  

    ctlhdl.log_files_text = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[15.36 40 193.92 17.28], ...
		'String','Mission Review Selection', ...
		'Style','text', ...
		'TooltipString', ...
		['Select a mission file for review'], ...
		'Tag','log_files_text');

  ctlhdl.data_text = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[60.48 90 104.64 13.44], ...
		'String','Data Directory', ...
		'Style','text', ...
		'Tag','data_text');    

    ctlhdl.uvclog_popupmenu = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Min',1, ...
		'Position',[10 15 200 26.64], ...
		'Callback','', ...
		'Style','popupmenu', ...
		'String','UVC log files', ...
		'Tag','uvclog_popupmenu', ...
		'Value',1);

  ctlhdl.lcmlog_popupmenu = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Min',1, ...
		'Position',[10 10 200 11], ...
		'Callback','', ...
		'Style','popupmenu', ...
		'String','lcmlog files', ...
		'Tag','lcmlog_popupmenu', ...
		'Value',1);    

    ctlhdl.go_pushbutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.1 0.9 0.1], ...
        'Position',[190 42 27 16], ...
        'Callback', 'gobutton_callback()', ...
		'Style','pushbutton', ...
		'String','Go!', ...
		'Tag','go_pushbutton');

    
  %================================  
  % mission stats text
  %================================  
  ctlhdl.stats_header_text = ...
    uicontrol('Parent',figctl, ...
	      'Units','points', ...
	      'BackgroundColor',[0.7 0.7 0.7], ...
	      'ListboxTop',0, ...
	      'Position',[234.24 87.36 194.88 17.28], ...
	      'String','Mission Stats', ...
	      'Style','text', ...
	      'Tag','stats_header_text');
  ctlhdl.stats_start_text = ...
    uicontrol('Parent',figctl, ...
	      'Units','points', ...
	      'BackgroundColor',[0.7 0.7 0.7], ...
	      'ListboxTop',0, ...
	      'Position',[234.24 73.36 194.88 17.28], ...
	      'String',' Start:', ...
	      'HorizontalAlignment','left', ...			      
	      'Style','text', ...
	      'Tag','stats_start_text');
  ctlhdl.stats_end_text = ...
    uicontrol('Parent',figctl, ...
	      'Units','points', ...
	      'BackgroundColor',[0.7 0.7 0.7], ...
	      'ListboxTop',0, ...
	      'Position',[234.24 60.36 194.88 17.28], ...
	      'String',' End:', ...
	      'HorizontalAlignment','left', ...
	      'Style','text', ...
	      'Tag','stats_end_text');
  ctlhdl.stats_divider_text = ...
    uicontrol('Parent',figctl, ...
	      'Units','points', ...
	      'BackgroundColor',[0.7 0.7 0.7], ...
	      'ListboxTop',0, ...
	      'Position',[234.24 47.36 194.88 17.28], ...
	      'String','--------------------------------------', ...
	      'Style','text', ...
	      'Tag','stats_header_text');
  ctlhdl.stats_elapsed_text = ...
    uicontrol('Parent',figctl, ...
	      'Units','points', ...
	      'BackgroundColor',[0.7 0.7 0.7], ...
	      'ListboxTop',0, ...
	      'Position',[234.24 34.36 194.88 17.28], ...
	      'String',sprintf(' Elapsed Time:'), ...
	      'HorizontalAlignment','left', ...
	      'Style','text', ...
	      'Tag','stats_elapsed_text');  


  %================================
  % setwin controls
  %================================  
  ctlhdl.setwin_frame = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[443.52 5.76 74.88 94.08], ...
		'Style','frame', ...
		'Tag','setwin_frame');
  ctlhdl.setwin_checkbox = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[450.24 75.24 57.60 24], ...
		'String','setwin', ...
		'Style','checkbox', ...
		'Value',0, ...
		'Callback', ...
		['ctlhdl = get(2,''UserData'');', ...
		 'if (get(ctlhdl.setwin_checkbox,''Value'') == 1);', ...
		 'figure(1);', ...
		 '[xmin,xmax] = setwin;', ...
		 'set(ctlhdl.setwin_checkbox,''UserData'',[xmin,xmax]);', ...
		 'clear xmin xmax ctlhdl;', ...
		 'end;', ...
		 ], ...
		'Tag','setwin_checkbox');
    ctlhdl.reset_mission_pushbutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'Callback', ...
		['user = get(1,''UserData'');', ...
         'ctlhdl = get(2,''UserData'');', ...
		 'set(ctlhdl.setwin_checkbox,''Value'',1);', ...
		 'figure(1);', ...
		 'range = setwin([0,user.ENDTIME-user.STARTTIME]);', ...
         'set(ctlhdl.review_slider,''Value'',-1);', ...
         'review_slider_callback();', ...
		 'clear ctlhdl;', ...
		 ], ...
		'ListboxTop',0, ...
		'Position',[458.88 55.52 42.24 20.04], ...
		'String','mission', ...
		'Tag','reset_mission_pushbutton');
  ctlhdl.reset_pushbutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'Callback', ...
		['user = get(1,''UserData'');', ...
         'ctlhdl = get(2,''UserData'');', ...
		 'set(ctlhdl.setwin_checkbox,''Value'',0);', ...
		 'figure(1);', ...
		 'setwin(''reset'');', ...
         'set(ctlhdl.review_slider,''Value'',-1);', ...
         'review_slider_callback();', ...
		 'SetHour;', ...
		 'clear ctlhdl;', ...
		 ], ...
		'ListboxTop',0, ...
		'Position',[458.88 30.52 42.24 20.04], ...
		'String','reset', ...
		'Tag','reset_pushbutton');
  ctlhdl.setwin_text = ...
    uicontrol('Parent',figctl, ...
	      'Units','points', ...
	      'BackgroundColor',[0.7 0.7 0.7], ...
	      'ListboxTop',0, ...
	      'Position',[451.2 6.6 56.64 18.24], ...
	      'String','Time Axis', ...
	      'Style','text', ...
	      'TooltipString', ...	      
	      ['Sets all time axes to a selected range'], ...	      
	      'Tag','setwin_text');
  
  
  %================================  
  % subplot controls
  %================================  
  ctlhdl.subplot_frame = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[526.08 5.76 78.72 94.08], ...
		'Style','frame', ...
		'Tag','subplot_frame');
  ctlhdl.top_radiobutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'Value',0, ...
		'Callback', ...
		['ctlhdl = get(2,''UserData'');', ...
		 'if (get(ctlhdl.top_radiobutton,''Value'') == 1);', ...
		 'set(ctlhdl.bottom_radiobutton,''Value'',0);', ...
		 'set(ctlhdl.full_radiobutton,''Value'',0);', ...
		 'else;', ...
		 'set(ctlhdl.top_radiobutton,''Value'',1);', ...
		 'end;', ...
		 'clear ctlhdl;', ...
		], ...
		'ListboxTop',0, ...
		'Position',[537.36 71.12 56.16 19.2], ...
		'String','Top', ...
		'HorizontalAlignment','left', ...
		'Style','radiobutton', ...
		'Tag','top_radiobutton');
  ctlhdl.bottom_radiobutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'Value',0, ...
		'Callback', ...
		['ctlhdl = get(2,''UserData'');', ...
		 'if (get(ctlhdl.bottom_radiobutton,''Value'') == 1);', ...
		 'set(ctlhdl.top_radiobutton,''Value'',0);', ...
		 'set(ctlhdl.full_radiobutton,''Value'',0);', ...
		 'else;', ...
		 'set(ctlhdl.bottom_radiobutton,''Value'',1);', ...
		 'end;', ...
		 'clear ctlhdl;', ...
		], ...
		'ListboxTop',0, ...
		'Position',[537.36 49.96 56.16 20.16], ...
		'String','Bottom', ...
		'HorizontalAlignment','left', ...		
		'Style','radiobutton', ...		
		'Tag','bottom_radiobutton');  
  ctlhdl.full_radiobutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'Value',1, ...
		'Callback', ...
		['ctlhdl = get(2,''UserData'');', ...
		 'if (get(ctlhdl.full_radiobutton,''Value'') == 1);', ...
		 'set(ctlhdl.top_radiobutton,''Value'',0);', ...
		 'set(ctlhdl.bottom_radiobutton,''Value'',0);', ...
		 'else;', ...
		 'set(ctlhdl.full_radiobutton,''Value'',1);', ...
		 'end;', ...
		 'clear ctlhdl;', ...
		], ...
		'ListboxTop',0, ...
		'Position',[537.36 29.76 56.12 19.2], ...
		'String','Full', ...
		'HorizontalAlignment','left', ...		
		'Style','radiobutton', ...		
		'Tag','full_radiobutton');
  ctlhdl.subplot_text = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[535.68 9.6 59.52 16.32], ...
		'String','Subplot', ...
		'Style','text', ...
		'TooltipString', ...
		['Sets the placement of the next graph'], ...
		'Tag','subplot_text');  

  
  %================================  
  % time format controls
  %================================  
  ctlhdl.time_frame = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[612.48 25.52 72 74.32], ...
		'Style','frame', ...
		'Tag','time_frame');
  ctlhdl.short_radiobutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'Value',0, ...
		'UserData',0, ...
		'Callback', ...
		['ctlhdl = get(2,''UserData'');', ...
		 'if (get(ctlhdl.short_radiobutton,''Value'') == 1);', ...
		   'set(ctlhdl.long_radiobutton,''Value'',0);', ...
		   'set(ctlhdl.abs_radiobutton,''Value'',0);', ...
		   'SetTimeAxisFormat;', ...
		   'if (get(ctlhdl.zoom_checkbox,''Value'') == 1)', ...
		     'set(ctlhdl.zoom_checkbox,''Value'',0);', ...
		     'figure(1);', ...
		     'zoom off;', ...
		   'end;', ...
		 'else;', ...
		   'set(ctlhdl.short_radiobutton,''Value'',1);', ...
		 'end;', ...
		 'clear ctlhdl;', ...
		], ...
		'ListboxTop',0, ...
		'Position',[622.08 77.8 53.76 17.28], ...
		'String','Short', ...
		'HorizontalAlignment','left', ...
		'Style','radiobutton', ...
		'Tag','short_radiobutton');
  ctlhdl.long_radiobutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[622.08 59.52 53.76 17.28], ...
		'String','Long', ...
		'HorizontalAlignment','left', ...		
		'Value',1, ...
		'Callback', ...
		['ctlhdl = get(2,''UserData'');', ...
		 'if (get(ctlhdl.long_radiobutton,''Value'') == 1);', ...
		   'set(ctlhdl.short_radiobutton,''Value'',0);', ...
		   'set(ctlhdl.abs_radiobutton,''Value'',0);', ... 
		   'SetTimeAxisFormat;', ...
		   'if (get(ctlhdl.zoom_checkbox,''Value'') == 1)', ...
		     'set(ctlhdl.zoom_checkbox,''Value'',0);', ...
		     'figure(1);', ...
		     'zoom off;', ...
		   'end;', ...		 
		 'else;', ...
		   'set(ctlhdl.long_radiobutton,''Value'',1);', ...
		 'end;', ...
		 'clear ctlhdl;', ...
		], ...
		'Style','radiobutton', ...
		'Tag','long_radiobutton');
  ctlhdl.abs_radiobutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[622.08 41.52 53.76 17.28], ...
		'String','Abs', ...
		'HorizontalAlignment','left', ...		
		'Value',0, ...
		'Callback', ...
		['ctlhdl = get(2,''UserData'');', ...
		 'if (get(ctlhdl.abs_radiobutton,''Value'') == 1);', ...
		   'set(ctlhdl.short_radiobutton,''Value'',0);', ...
		   'set(ctlhdl.long_radiobutton,''Value'',0);', ...
		   'SetTimeAxisFormat;', ...
		   'if (get(ctlhdl.zoom_checkbox,''Value'') == 1)', ...
		     'set(ctlhdl.zoom_checkbox,''Value'',0);', ...
		     'figure(1);', ...
		     'zoom off;', ...
		   'end;', ...		 
		 'else;', ...
		   'set(ctlhdl.abs_radiobutton,''Value'',1);', ...
		 'end;', ...
		 'clear ctlhdl;', ...
		], ...
		'Style','radiobutton', ...
		'Tag','abs_radiobutton');  
  ctlhdl.time_text = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[624 30.36 51.84 10.36], ...
		'String','Time', ...
		'Style','text', ...
		'TooltipString', ...
		['Controls the formatting of the time axis'], ...
		'Tag','time_text');  
  
  
  %================================  
  % drag checkbox
  %================================  
  ctlhdl.grid_checkbox = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[651.12 2.64 43.76 20.08], ...
		'String','Drag', ...
		'FontSize',9, ...
		'Style','checkbox', ...
		'Value', 0, ...
		'Callback',...
		['ctlhdl = get(2, ''UserData'');',...
		 'if (get(ctlhdl.grid_checkbox,''Value'') == 1)', ...
		 'set(ctlhdl.short_radiobutton,''Value'',1);', ...
		 'set(ctlhdl.long_radiobutton,''Value'',0);', ...
		 'set(ctlhdl.abs_radiobutton,''Value'',0);', ...
		 'set(ctlhdl.zoom_checkbox,''Value'',0);',...
		 'end;',...
		 'SetDrag;', ...
		 'clear ctlhdl;',...
		],...
		'Tag','grid_checkbox');
  
  %================================  
  % zoom checkbox
  %================================
  ctlhdl.zoom_checkbox = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[607.12 2.64 43.76 20.08], ...
		'Style','checkbox', ...
		'String','Zoom', ...
		'FontSize',9, ...
		'Value', 0, ...
		'Callback', ...
		['ctlhdl = get(2,''UserData'');', ...
		 'if (get(ctlhdl.zoom_checkbox,''Value'') == 1)', ...
		 'set(ctlhdl.short_radiobutton,''Value'',1);', ...
		 'set(ctlhdl.long_radiobutton,''Value'',0);', ...
		 'set(ctlhdl.abs_radiobutton,''Value'',0);', ...
		 'set(ctlhdl.grid_checkbox,''Value'',0);',...
		 'SetTimeAxisFormat;', ...
		 'end;', ...
		 'SetZoom;',...
		 'clear ctlhdl;', ...
		 ], ...
		'TooltipString', ...
		['Zoom controls'], ...
		'Tag','zoom_checkbox');

  %================================  
  % quit button
  %================================  
  ctlhdl.quit_pushbutton = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[374.4 8.64 58.56 23.04], ...
		'String','Quit', ...
		'Callback', ...
		['pos(1,:) = get(1,''Position'');', ...
		 'pos(2,:) = get(2,''Position'');', ...
		 'pos(3,:) = get(3,''Position'');', ...
         'user = get(1,''UserData'');', ...
		 'save([user.rootdir,''.iver2plot.dat''],''pos'',''-ASCII'');', ...
		 'close(1); close(2); close(3);', ...
		 'clear pos user;', ...
		], ...
		'Tag','quit_pushbutton');


  %================================  
  % review controls
  %================================  
  ctlhdl.review_value_text = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[255.4 17.64 68.56 13.04], ...
		'String','Hour: ALL', ...
		'Style','Text', ...
		'TooltipString', ...
		['Segment the data into 1 hour blocks of time'], ...		
		'Tag','review_value_text');
  ctlhdl.review_all_text = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[228.4 3.64 13.56 13.04], ...
		'String','A', ...
		'Style','Text', ...
		'Tag','review_all_text');
  ctlhdl.review_max_text = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[332.4 3.64 25.56 13.04], ...
		'String','10', ...
		'Style','Text', ...
		'Tag','review_slider');
  ctlhdl.review_slider = ...
      uicontrol('Parent',figctl, ...
		'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
		'ListboxTop',0, ...
		'Position',[240.4 2.64 95.56 17.04], ...
		'Style','Slider', ...
		'Min', -1, ...
		'Max', 10, ...
		'Value',-1, ...
		'UserData',-1, ...
		'Callback', 'review_slider_callback(); SetHour;', ...
		'Tag','review_slider');

  
%   % NO_VALUE format controls
%   %================================  
%   ctlhdl.novalue_frame = ...
%       uicontrol('Parent',figctl, ...
% 		'Units','points', ...
% 		'BackgroundColor',[0.7 0.7 0.7], ...
% 		'ListboxTop',0, ...
% 		'Position',[692.48 25.52 65 74.32], ...
% 		'Style','frame', ...
% 		'Tag','novalue_frame');
%   ctlhdl.novalue98765_radiobutton = ...
%       uicontrol('Parent',figctl, ...
% 		'Units','points', ...
% 		'BackgroundColor',[0.7 0.7 0.7], ...
% 		'Value',0, ...
% 		'UserData',0, ...
% 		'Callback', ...
% 		['ctlhdl = get(2,''UserData'');', ...
% 		 'if (get(ctlhdl.novalue98765_radiobutton,''Value'') == 1);', ...
% 		   'set(ctlhdl.novalue12345_radiobutton,''Value'',0);', ...
% 		 'end;', ...
% 		 'clear ctlhdl;', ...
% 		], ...
% 		'ListboxTop',0, ...
% 		'Position',[700.08 77.8 55.76 17.28], ...
% 		'String','-98765', ...
% 		'HorizontalAlignment','left', ...
% 		'Style','radiobutton', ...
% 		'Tag','novalue98765_radiobutton');
%   ctlhdl.novalue12345_radiobutton = ...
%       uicontrol('Parent',figctl, ...
% 		'Units','points', ...
% 		'BackgroundColor',[0.7 0.7 0.7], ...
% 		'ListboxTop',0, ...
% 		'Position',[700.08 59.52 55.76 17.28], ...
% 		'String','-12345', ...
% 		'HorizontalAlignment','left', ...		
% 		'Value',1, ...
% 		'Callback', ...
% 		['ctlhdl = get(2,''UserData'');', ...
% 		 'if (get(ctlhdl.novalue12345_radiobutton,''Value'') == 1);', ...
% 		   'set(ctlhdl.novalue98765_radiobutton,''Value'',0);', ...
% 		 'end;', ...
% 		 'clear ctlhdl;', ...
% 		], ...
% 		'Style','radiobutton', ...
% 		'Tag','novalue12345_radiobutton');
%   ctlhdl.novalue_text = ...
%       uicontrol('Parent',figctl, ...
% 		'Units','points', ...
% 		'BackgroundColor',[0.7 0.7 0.7], ...
% 		'ListboxTop',0, ...
% 		'Position',[700 30.36 51.84 10.36], ...
% 		'String','NO_VALUE', ...
% 		'Style','text', ...
% 		'TooltipString', ...
% 		['Controls the formatting of the time axis'], ...
% 		'Tag','novalue_text');  

  set(2,'UserData',ctlhdl);
