function print_recovered_pose(rph_nav,t_nav,rph_img,t_img)

fprintf(['\tNAV\tIMG\t\t\tNAV\tIMG\n', ...
	 'R | %+.6f\t%+.6f |\tX | %+.6f\t%+.6f |\n', ...
	 'P | %+.6f\t%+.6f |\tY | %+.6f\t%+.6f |\n', ...
	 'H | %+.6f\t%+.6f |\tZ | %+.6f\t%+.6f |\n'], ...	     
	rph_nav(1)*180/pi,rph_img(1)*180/pi,t_nav(1),t_img(1), ...
	rph_nav(2)*180/pi,rph_img(2)*180/pi,t_nav(2),t_img(2), ...
	rph_nav(3)*180/pi,rph_img(3)*180/pi,t_nav(3),t_img(3));
