#! /bin/bash
################################################################
# Script for creating a new origin for the diver rig.
# It creates a backup of the current origin file:
# $ORIGINDIR/$CURRENTORIGIN:
#
# Usage: 
#   new_origin_diver.sh <ORIGIN_NAME> <LAT> <LON>
#
# History
#   2011-06-15          ALF         created
#
################################################################

# Setup file location variables
ORIGINDIR="/home/auv/git/acfr_lcm/config/origins/d2"
CURRENTORIGIN="current_origin.conf"
CURRENTORIGINFILE=$ORIGINDIR/$CURRENTORIGIN

# Check for right number of arguments, otherwise print usage.
if [ $# -ne 3 ]; then
    echo -e "
`basename $0`
Script for creating a new origin for the diver rig.
It backs up and replaces the current origin file:

\"$ORIGINDIR/$CURRENTORIGIN\"

Usage: 
    `basename $0` <ORIGIN_NAME> <LAT> <LON>

Current ORIGIN file contains:
----------------------------------------------------------------
`cat $CURRENTORIGINFILE`
----------------------------------------------------------------
"
    exit
fi

# Get input arguments
NEWORIGIN=$1
LAT=$2
LON=$3

# TODO: check format of input arguments

# Backup old conf file
TIMESTAMP=`cat $CURRENTORIGINFILE | grep ORIGIN_TIMESTAMP | cut -d '=' -f 2 | sed 's/\"//g'`
OLDNAME=`cat $CURRENTORIGINFILE | grep ORIGIN_NAME | cut -d '=' -f 2 | sed 's/\"//g'`
OLDORIGINFILE=$ORIGINDIR/${TIMESTAMP}_${OLDNAME}.conf
cp $CURRENTORIGINFILE $OLDORIGINFILE        # copy and rename old file
#svn add $OLDORIGINFILE                     # add it to the svn repo


# Print out new conf file
echo -e "# This file is automatically generated by
# the `basename $0` script on `date --utc +%Y/%m/%d\ %H\:%M\:%S`

#ORIGIN_TIMESTAMP=\"`date --utc +%Y%m%d_%H%M%S`\"
ORIGIN_NAME=\"$NEWORIGIN\"
ORIGIN_LAT=\"$LAT\"
ORIGIN_LNG=\"$LON\"
" > $CURRENTORIGINFILE
