// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "bmsCAN_data.h"

static int __bmsCAN_data_hash_computed;
static uint64_t __bmsCAN_data_hash;

uint64_t __bmsCAN_data_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __bmsCAN_data_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__bmsCAN_data_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xaa9d3239c5c7b79aLL
         + __int16_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __byte_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __byte_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __bmsCAN_data_get_hash(void)
{
    if (!__bmsCAN_data_hash_computed) {
        __bmsCAN_data_hash = (int64_t)__bmsCAN_data_hash_recursive(NULL);
        __bmsCAN_data_hash_computed = 1;
    }

    return __bmsCAN_data_hash;
}

int __bmsCAN_data_encode_array(void *buf, int offset, int maxlen, const bmsCAN_data *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].bms), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].error), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, &(p[element].soc), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].voltage), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].current), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, &(p[element].temp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt1), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt2), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt3), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt4), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt5), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt6), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt7), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt8), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt9), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt10), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt11), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt12), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt13), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt14), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int bmsCAN_data_encode(void *buf, int offset, int maxlen, const bmsCAN_data *p)
{
    int pos = 0, thislen;
    int64_t hash = __bmsCAN_data_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __bmsCAN_data_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __bmsCAN_data_encoded_array_size(const bmsCAN_data *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int16_t_encoded_array_size(&(p[element].bms), 1);

        size += __string_encoded_array_size(&(p[element].error), 1);

        size += __byte_encoded_array_size(&(p[element].soc), 1);

        size += __float_encoded_array_size(&(p[element].voltage), 1);

        size += __float_encoded_array_size(&(p[element].current), 1);

        size += __byte_encoded_array_size(&(p[element].temp), 1);

        size += __float_encoded_array_size(&(p[element].cvolt1), 1);

        size += __float_encoded_array_size(&(p[element].cvolt2), 1);

        size += __float_encoded_array_size(&(p[element].cvolt3), 1);

        size += __float_encoded_array_size(&(p[element].cvolt4), 1);

        size += __float_encoded_array_size(&(p[element].cvolt5), 1);

        size += __float_encoded_array_size(&(p[element].cvolt6), 1);

        size += __float_encoded_array_size(&(p[element].cvolt7), 1);

        size += __float_encoded_array_size(&(p[element].cvolt8), 1);

        size += __float_encoded_array_size(&(p[element].cvolt9), 1);

        size += __float_encoded_array_size(&(p[element].cvolt10), 1);

        size += __float_encoded_array_size(&(p[element].cvolt11), 1);

        size += __float_encoded_array_size(&(p[element].cvolt12), 1);

        size += __float_encoded_array_size(&(p[element].cvolt13), 1);

        size += __float_encoded_array_size(&(p[element].cvolt14), 1);

    }
    return size;
}

int bmsCAN_data_encoded_size(const bmsCAN_data *p)
{
    return 8 + __bmsCAN_data_encoded_array_size(p, 1);
}

int __bmsCAN_data_decode_array(const void *buf, int offset, int maxlen, bmsCAN_data *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].bms), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].error), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, &(p[element].soc), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].voltage), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].current), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, &(p[element].temp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt1), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt2), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt3), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt4), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt5), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt6), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt7), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt8), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt9), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt10), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt11), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt12), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt13), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cvolt14), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __bmsCAN_data_decode_array_cleanup(bmsCAN_data *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_decode_array_cleanup(&(p[element].bms), 1);

        __string_decode_array_cleanup(&(p[element].error), 1);

        __byte_decode_array_cleanup(&(p[element].soc), 1);

        __float_decode_array_cleanup(&(p[element].voltage), 1);

        __float_decode_array_cleanup(&(p[element].current), 1);

        __byte_decode_array_cleanup(&(p[element].temp), 1);

        __float_decode_array_cleanup(&(p[element].cvolt1), 1);

        __float_decode_array_cleanup(&(p[element].cvolt2), 1);

        __float_decode_array_cleanup(&(p[element].cvolt3), 1);

        __float_decode_array_cleanup(&(p[element].cvolt4), 1);

        __float_decode_array_cleanup(&(p[element].cvolt5), 1);

        __float_decode_array_cleanup(&(p[element].cvolt6), 1);

        __float_decode_array_cleanup(&(p[element].cvolt7), 1);

        __float_decode_array_cleanup(&(p[element].cvolt8), 1);

        __float_decode_array_cleanup(&(p[element].cvolt9), 1);

        __float_decode_array_cleanup(&(p[element].cvolt10), 1);

        __float_decode_array_cleanup(&(p[element].cvolt11), 1);

        __float_decode_array_cleanup(&(p[element].cvolt12), 1);

        __float_decode_array_cleanup(&(p[element].cvolt13), 1);

        __float_decode_array_cleanup(&(p[element].cvolt14), 1);

    }
    return 0;
}

int bmsCAN_data_decode(const void *buf, int offset, int maxlen, bmsCAN_data *p)
{
    int pos = 0, thislen;
    int64_t hash = __bmsCAN_data_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __bmsCAN_data_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int bmsCAN_data_decode_cleanup(bmsCAN_data *p)
{
    return __bmsCAN_data_decode_array_cleanup(p, 1);
}

int __bmsCAN_data_clone_array(const bmsCAN_data *p, bmsCAN_data *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_clone_array(&(p[element].bms), &(q[element].bms), 1);

        __string_clone_array(&(p[element].error), &(q[element].error), 1);

        __byte_clone_array(&(p[element].soc), &(q[element].soc), 1);

        __float_clone_array(&(p[element].voltage), &(q[element].voltage), 1);

        __float_clone_array(&(p[element].current), &(q[element].current), 1);

        __byte_clone_array(&(p[element].temp), &(q[element].temp), 1);

        __float_clone_array(&(p[element].cvolt1), &(q[element].cvolt1), 1);

        __float_clone_array(&(p[element].cvolt2), &(q[element].cvolt2), 1);

        __float_clone_array(&(p[element].cvolt3), &(q[element].cvolt3), 1);

        __float_clone_array(&(p[element].cvolt4), &(q[element].cvolt4), 1);

        __float_clone_array(&(p[element].cvolt5), &(q[element].cvolt5), 1);

        __float_clone_array(&(p[element].cvolt6), &(q[element].cvolt6), 1);

        __float_clone_array(&(p[element].cvolt7), &(q[element].cvolt7), 1);

        __float_clone_array(&(p[element].cvolt8), &(q[element].cvolt8), 1);

        __float_clone_array(&(p[element].cvolt9), &(q[element].cvolt9), 1);

        __float_clone_array(&(p[element].cvolt10), &(q[element].cvolt10), 1);

        __float_clone_array(&(p[element].cvolt11), &(q[element].cvolt11), 1);

        __float_clone_array(&(p[element].cvolt12), &(q[element].cvolt12), 1);

        __float_clone_array(&(p[element].cvolt13), &(q[element].cvolt13), 1);

        __float_clone_array(&(p[element].cvolt14), &(q[element].cvolt14), 1);

    }
    return 0;
}

bmsCAN_data *bmsCAN_data_copy(const bmsCAN_data *p)
{
    bmsCAN_data *q = (bmsCAN_data*) malloc(sizeof(bmsCAN_data));
    __bmsCAN_data_clone_array(p, q, 1);
    return q;
}

void bmsCAN_data_destroy(bmsCAN_data *p)
{
    __bmsCAN_data_decode_array_cleanup(p, 1);
    free(p);
}

int bmsCAN_data_publish(lcm_t *lc, const char *channel, const bmsCAN_data *p)
{
      int max_data_size = bmsCAN_data_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = bmsCAN_data_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _bmsCAN_data_subscription_t {
    bmsCAN_data_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void bmsCAN_data_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    bmsCAN_data p;
    memset(&p, 0, sizeof(bmsCAN_data));
    status = bmsCAN_data_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding bmsCAN_data!!!\n", status);
        return;
    }

    bmsCAN_data_subscription_t *h = (bmsCAN_data_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    bmsCAN_data_decode_cleanup (&p);
}

bmsCAN_data_subscription_t* bmsCAN_data_subscribe (lcm_t *lcm,
                    const char *channel,
                    bmsCAN_data_handler_t f, void *userdata)
{
    bmsCAN_data_subscription_t *n = (bmsCAN_data_subscription_t*)
                       malloc(sizeof(bmsCAN_data_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 bmsCAN_data_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg bmsCAN_data LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int bmsCAN_data_subscription_set_queue_capacity (bmsCAN_data_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int bmsCAN_data_unsubscribe(lcm_t *lcm, bmsCAN_data_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe bmsCAN_data_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

