// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _bmsCAN_data_h
#define _bmsCAN_data_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _bmsCAN_data bmsCAN_data;
struct _bmsCAN_data
{
    int16_t    bms;
    char*      error;
    uint8_t    soc;
    float      voltage;
    float      current;
    uint8_t    temp;
    float      cvolt1;
    float      cvolt2;
    float      cvolt3;
    float      cvolt4;
    float      cvolt5;
    float      cvolt6;
    float      cvolt7;
    float      cvolt8;
    float      cvolt9;
    float      cvolt10;
    float      cvolt11;
    float      cvolt12;
    float      cvolt13;
    float      cvolt14;
};

/**
 * Create a deep copy of a bmsCAN_data.
 * When no longer needed, destroy it with bmsCAN_data_destroy()
 */
bmsCAN_data* bmsCAN_data_copy(const bmsCAN_data* to_copy);

/**
 * Destroy an instance of bmsCAN_data created by bmsCAN_data_copy()
 */
void bmsCAN_data_destroy(bmsCAN_data* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _bmsCAN_data_subscription_t bmsCAN_data_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * bmsCAN_data is received.
 */
typedef void(*bmsCAN_data_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const bmsCAN_data *msg, void *userdata);

/**
 * Publish a message of type bmsCAN_data using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int bmsCAN_data_publish(lcm_t *lcm, const char *channel, const bmsCAN_data *msg);

/**
 * Subscribe to messages of type bmsCAN_data using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is received.
 *                This function is invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
bmsCAN_data_subscription_t* bmsCAN_data_subscribe(lcm_t *lcm, const char *channel, bmsCAN_data_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by bmsCAN_data_subscribe()
 */
int bmsCAN_data_unsubscribe(lcm_t *lcm, bmsCAN_data_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int bmsCAN_data_subscription_set_queue_capacity(bmsCAN_data_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type bmsCAN_data into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to bmsCAN_data_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int bmsCAN_data_encode(void *buf, int offset, int maxlen, const bmsCAN_data *p);

/**
 * Decode a message of type bmsCAN_data from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with bmsCAN_data_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int bmsCAN_data_decode(const void *buf, int offset, int maxlen, bmsCAN_data *msg);

/**
 * Release resources allocated by bmsCAN_data_decode()
 * @return 0
 */
int bmsCAN_data_decode_cleanup(bmsCAN_data *p);

/**
 * Check how many bytes are required to encode a message of type bmsCAN_data
 */
int bmsCAN_data_encoded_size(const bmsCAN_data *p);

// LCM support functions. Users should not call these
int64_t __bmsCAN_data_get_hash(void);
uint64_t __bmsCAN_data_hash_recursive(const __lcm_hash_ptr *p);
int     __bmsCAN_data_encode_array(void *buf, int offset, int maxlen, const bmsCAN_data *p, int elements);
int     __bmsCAN_data_decode_array(const void *buf, int offset, int maxlen, bmsCAN_data *p, int elements);
int     __bmsCAN_data_decode_array_cleanup(bmsCAN_data *p, int elements);
int     __bmsCAN_data_encoded_array_size(const bmsCAN_data *p, int elements);
int     __bmsCAN_data_clone_array(const bmsCAN_data *p, bmsCAN_data *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
