# tcl file that loads a configuration file for texture mapping in vtk
# configuration file generated by matlab after bundle adjustment

# 20040302 OP Modified to be run after a configuration script that sets
#             file names up
# 20040206 OP Created

# first we load in the standard vtk packages into tcl
#package require vtk
#package require vtkinteraction
#package require vtktesting

# open config file
set texture_config [open $tex_file r]
#set texture_config [open "../texture_config20040209.dat" r]
#set texture_config [open "../../test_loop20040214.dat" r]
# directory for texture from first line of texture_config
gets $texture_config texture_dir
set j 1
set i 1

while {[gets $texture_config line] >= 0}  {

    #while {$i <= 40} {}
#   gets $texture_config line
    puts "Processing Texture Image$i"
    # points for camera clipping
    vtkPoints points$i
 
    scan $line "%f %f %f" x y z
       points$i InsertNextPoint $x $y $z
    for {set j 1} {$j <= 5 } {incr j} {
	scan [gets $texture_config] "%f %f %f" x y z
	points$i InsertNextPoint $x $y $z
    }
    # normals for camera clipping
    vtkFloatArray normals$i
       normals$i SetNumberOfComponents 3
    for {set j 1} {$j <= 6} {incr j} {
	scan [gets $texture_config] "%f %f %f" x y z
        normals$i InsertNextTuple3 $x $y $z
    }
    # planes for camera clipping
    vtkPlanes planes$i
       planes$i SetPoints points$i
       planes$i SetNormals normals$i
    # image texture reader
    vtkPNGReader pngReader$i
       pngReader$i SetFileName $texture_dir[gets $texture_config]
    # texture object
    vtkTexture tex$i
       tex$i SetInput [pngReader$i GetOutput]
       tex$i SetRepeat 0
    # clipped polygonal mesh
    vtkClipPolyData clipper$i
       clipper$i SetInput [meshNormals GetOutput]
       clipper$i SetClipFunction planes$i
       clipper$i InsideOutOn
    # texture projector
    vtkProjectedTexture cam$i
       cam$i SetInput [clipper$i GetOutput]
    scan [gets $texture_config] "%f %f %f" x y z
       cam$i SetPosition $x $y $z
    scan [gets $texture_config] "%f %f %f" x y z
       cam$i SetFocalPoint $x $y $z
    scan [gets $texture_config] "%f %f %f" x y z
       cam$i SetUp $x $y $z
    scan [gets $texture_config] "%f %f %f" x y z
       cam$i SetAspectRatio $x $y $z
    # mapper
    vtkPolyDataMapper clipMapper$i
       clipMapper$i SetInput [cam$i GetOutput]
    # actor
    vtkActor clipActor$i
       clipActor$i SetMapper clipMapper$i
       clipActor$i SetTexture tex$i
    # add to renderer, (used to be 4 now every)
    incr j
    #if {$j == 4} {
       ren1 AddActor clipActor$i
       set j 1
    #}
    incr i
}

close $texture_config

