macro (perlsx_opencv)
    find_package(OpenCV REQUIRED)
  #perlsx_find_package (OpenCV "on ubuntu `sudo apt-get install libcv-dev libcvaux-dev libhighgui-dev`" ${ARGN})
  if (OpenCV_FOUND)
    include_directories (${OpenCV_INCLUDE_DIR})
    set (PERLSX_OPENCV ${OpenCV_LIBS})
    #message ("version ${OpenCV_VERSION_MAJOR}${OpenCV_VERSION_MINOR}${OpenCV_VERSION_PATCH}")
    add_definitions ("-D OpenCV_VERSION=${OpenCV_VERSION_MAJOR}${OpenCV_VERSION_MINOR}${OpenCV_VERSION_PATCH}")
  endif ()
endmacro ()
