macro (perlsx_ncurses)
  set (CURSES_NEED_NCURSES TRUE)
  perlsx_find_package (CURSES "on ubuntu `sudo apt-get install libcurses-dev`" ${ARGN})
  if (CURSES_FOUND)
    include_directories (${CURSES_LIBRARIES})
    set (PERLSX_NCURSES ${CURSES_LIBRARIES})
  endif ()
endmacro ()
